name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd builder
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          cd ..

      - name: Run Black check
        run: |
          cd builder
          black --check .

      - name: Run isort check
        run: |
          cd builder
          isort --check-only --profile black .

      - name: Run Flake8
        run: |
          cd builder
          flake8 .

      - name: Run mypy
        run: |
          cd builder
          mypy .

  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd interface
          npm ci

      - name: Run ESLint (si vous avez ESLint dans interface/)
        run: |
          cd interface
          npx eslint . --ext .js,.jsx,.ts,.tsx --config .eslintrc.json

      - name: Run Prettier check
        run: |
          cd interface
          npm run format:check  # ou une commande équivalente
