name: Deploy FastAPI → Scaleway

on:
  push:
    paths:
      - 'builder/**'
      - 'survey_template/**'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        run: |
          echo "${{ secrets.SCW_SECRET_KEY }}" | docker login rg.fr-par.scw.cloud -u nologin --password-stdin

      - name: Build Docker image
        run: |
          docker build -t rg.fr-par.scw.cloud/builder-namespace/germina-backend:${{ github.sha }} ./builder

      - name: Push Docker image to Scaleway Registry
        run: |
          docker push rg.fr-par.scw.cloud/builder-namespace/germina-backend:${{ github.sha }}
      
      - name: Update Scaleway Serverless Container image
        run: |
          scw container container update bd063f12-f4a4-4fa9-b037-a76d12361d72 \
            image=rg.fr-par.scw.cloud/builder-namespace/germina-backend:${{ github.sha }}
