name: Deploy FastAPI → Cloud Run

on:
  push:
    paths:
      - 'builder/**'
      - 'survey_template/**'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build & Push Docker image
        env:
          IMAGE: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/germina-backend/builder:${{ github.sha }}
        run: |
          docker build -t $IMAGE builder/
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy builder \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/germina-backend/builder:${{ github.sha }} \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
            --timeout=300