name: Deploy FastAPI → Cloud Run

on:
  push:
    paths:
      - 'builder/**'
      - 'survey_template/**'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          auth_method: service_account
          export_default_credentials: true   # facultatif si vous n'avez pas besoin d'ADC ailleurs

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          gcloud builds submit builder \
            --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/germina-backend:${{ github.sha }}" \
            --quiet

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/germina-backend:${{ github.sha }}"

      - name: Fetch secrets from Secret Manager
        run: |
          echo "SUPABASE_URL=$(gcloud secrets versions access latest --secret='supabase-url')" >> $GITHUB_ENV
          echo "SUPABASE_KEY=$(gcloud secrets versions access latest --secret='supabase-key')" >> $GITHUB_ENV
          echo "SCW_SECRET_KEY=$(gcloud secrets versions access latest --secret='scw-secret-key')" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy germina-backend \
            --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/germina-backend:${{ github.sha }}" \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "SUPABASE_URL=${{ env.SUPABASE_URL }}" \
            --set-env-vars "SUPABASE_KEY=${{ env.SUPABASE_KEY }}" \
            --set-env-vars "SCW_SECRET_KEY=${{ env.SCW_SECRET_KEY }}"
