name: Deploy FastAPI → Cloud Run

on:
  push:
    paths:
      - 'builder.py'
      - 'survey_template/**'
      - 'Dockerfile'
      - 'requirements.txt'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build & Push Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/germina-backend:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy germina-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/germina-backend:${{ github.sha }} \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
