name: Deploy FastAPI → Cloud Run

on:
  push:
    paths:
      - 'builder/**'
      - 'survey_template/**'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build & Push Docker image
        env:
          IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/germina-backend:${{ github.sha }}
        run: |
          docker build -t $IMAGE builder/
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy germina-backend \
            --image $IMAGE \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
